name: Extract Native Headers

on:
  workflow_dispatch:

jobs:
  extract:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            task: extract_mac
          - os: ubuntu-latest
            task: extract_linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v1

      - uses: sdkman/sdkman-action@main
        id: sdkman
        with:
          candidate: jextract
          version: 22.ea.6
      - name: Configure environment
        shell: bash
        run: |
          echo "${{ steps.sdkman.outputs.path }}" >> $GITHUB_PATH

      - name: Run extract task
        run: |
          cd core
          just ${{ matrix.task }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        commit_message: Updated native headers for ${{ matrix.os }}
